### PR TITLE
[REGRESSION] Unbreak yarn builds when migrating to yarn stable by regressing to non-lazy emoji-mart

### PR DESCRIPTION
**Pull request by aescling**
Upstream mastodon has been using a fork of emoji-mart that supports lazy-loading emoji{s,m}. Unfortunately, it is presently breaking builds when using yarn>=2, which is required by the asset precompilation script as of Mastodon 3.5.0. Using upstream emoji-mart unbreaks the build, so I suppose we must deal with the performance loss.

The emoji-mart fork&#x2019;s issue appears to simply be its version number (!?), so we could *try* hosting a fork and changing the version number to something yarn (or is it npm?) will accept, and using a git link in the `package.json`.

### CODE REVIEW

**Comment by marrus-sh** [comment]
~~or use a git link to a commit hash with no version number~~

when i actually get a running mastodon on my computer again i’ll try to look into this

**Comment by single-right-quote** [comment]
> ~or use a git link to a commit hash with no version number~

i tried that and yard complained about the version number anyway

**Comment by single-right-quote** [comment]
this PR merge conflicts with glitch-soc 3.5.1&#x2019;s `yarn.lock`

**Comment by single-right-quote** [comment]
> this PR merge conflicts with glitch-soc 3.5.1’s `yarn.lock`

now using upstream's yarn.lock

**Comment by aescling** [comment]
`yarn set version latest` gets around this problem

this directly contradicts upstream&#x2019;s instructions to use `stable` (a change made basically at the time of 3.5.0&#x2019;s release), but works. we should raise an issue about this.

**Pull request closed without merging**
